Workingbranch st2180
sjt-85/NewBank pull request #5
Opened 2020-03-13 11:10 UTC by st2180

Implement a test for _As a user I want to be able to view my accounts so that I can see my balances_.

2020-03-13 20:34 UTC, sjt-85 requested changes
Hi Shinichi,

Looking good.  I'll have a go at making my own test classes later using your new feature.

Just a couple of things to tweak:
1.  can you fix the indentation to 2 spaces please?
2.  it's generating warnings in Eclipse due to the use of the raw type Class ("Class is a raw type.  References to generic type Class\<T\> should be parameterized").  It seems happy with Class\<?\> instead of Class.  Could you have a look please and check it all works with Class\<?\>?

Thanks

2020-03-13 23:24 UTC, st2180 commented
I format the code using a tool, and I change the type Class to Class<?>. Could you check them out?

2020-03-14 09:40 UTC, sjt-85 commented on newbank/test/ServerTestScenarios.java
> +    newbank.test.NBUnit.AssertEqual("Main: 1000.0" + System.lineSeparator(), bhagy);
Hi Shinichi sorry one last thing then it's ready to merge... to make your test compatible with the password feature recently added can you change the test login credentials to checkLogInDetails("Bhagy", **"1"**) and checkLogInDetails("Christina", **"2"**) please?

2020-03-14 10:48 UTC, st2180 commented
Hi Simon, I changed the things and a few others. Thanks.

2020-03-14 10:53 UTC, sjt-85 approved these changes

2020-03-14 10:54 UTC, merged